[package]
name = "acdc-file"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/qwertzer12/acdc-file"

[dependencies]

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
